### ISSUE TITLE
How do I nstalll these libraries, as an end user?

### ISSUE THREAD

**Issue by abendigo** [mikeseven/node-native-graphics-deps#1]
As a user who is not interested in recompiling node-webgl, or it's dependencies, how do I install these libraries (in 64 bit windows 7) such that I can start experimenting eith the sample code?

P.S. Thanks for making this available!

**Comment by mikeseven** [comment]
These libraries are precompiled for windows 7 32b and 64b. The simplest way
is to drop them in your windows/system folder for 32b versions and
windows/system/x64 for 64b versions.

This way, if you install node 32b (default) or 64b, the right libraries
will be dynamically linked.

-- Mike

**Comment by abendigo** [comment]
Thanks for the reply. Unfortunately, I really am lost here. under C:\Windows, I have a System32 directory, but not a System directory. There is also no x64 directory. 

I copied the files into the C:\Windows\System32 directory, assuming that is what you were referring too. But I am not sure how to tell node where the webgl module is.

**Comment by abendigo** [comment]
I have made more progress. I needed to install Visual Studio. I copied the files as suggested in your readme, and am now getting an error looking for WCOMP.lib.

**Comment by abendigo** [comment]
I meant VCOMP.dll above. Turns out, it's not included in Visual Studio Express. Only Pro or better. I am currently downloading a 90 day demo of Visual Studio 2012 Prof. Hopefully it will help.
